use std::fs;
use std::io::Write;
use dirs::home_dir;

static NOPE_DOT_VIM: &'static str = include_str!("./syntax/nope.vim");

pub fn install_vim_plugin () -> std::io::Result<()> {
    let home = home_dir().expect("can't find home dir");
    fs::create_dir_all(home.join(".vim/syntax/"))?;
    let mut nope_vim = fs::OpenOptions::new()
        .read(true)
        .write(true)
        .create(true)
        .open(home.join(".vim/syntax/nope.vim"))?;
    nope_vim.write_all(NOPE_DOT_VIM.as_bytes())?;

    if let Ok(vimrc) = fs::read_to_string(home.join(".vimrc")) {
        if vimrc.contains(
            "autocmd BufNewFile,BufRead *.nope setlocal ft=nope"
        ) || vimrc.contains(
            "autocmd BufNewFile,BufRead *.nope setlocal filetype=nope"
        ) {
            println!("The vim syntax highlighting plugin has been updated");
            return Ok(());
        }
    }

    let mut vimrc = fs::OpenOptions::new()
        .read(true)
        .create(true)
        .append(true)
        .open(home.join(".vimrc"))?;

    vimrc.write_all(
        "\n\
         \" Autogenerated by nope, do not modify.\n\
         autocmd BufNewFile,BufRead *.nope setlocal ft=nope\n\
         \n\
         ".as_bytes()
    )?;

    println!("Vim syntax highlighting installed for .nope files");

    Ok(())
}
